// Code generated by goswitch/layouts/generator. DO NOT EDIT.

//go:generate go run ./generator

// Package layouts holds the generated EN↔RU key-position tables used to
// correct text typed in the wrong layout (CORR-08).
package layouts

// ENToRU maps a character typed on the us(basic) XKB layout to the character
// at the same key position of the effective ru layout (winkeys, the default
// variant on Ubuntu 24.04). Both shift levels are merged into one map; the
// join is by key position, not by character.
var ENToRU = map[rune]rune{}

// RUToEN maps a character typed on the effective ru (winkeys) layout to the
// character at the same key position of us(basic). Position-inverse of ENToRU.
var RUToEN = map[rune]rune{}
